### PR TITLE
Support Godot 4

### PR DESCRIPTION
**Pull request by otDan**
Add Godot 4 support, probably needs a new branch on your repo depending on how you want to handle it

### CODE REVIEW

**Comment by otDan** [comment]
thanks, can you release this version on the asset lib?

**Comment by db0** [comment]
I'll see if I can look around and see how it's handled when you want to support both godot versions. If you find out before me, please let me know

**Comment by otDan** [comment]
from what I can see those are separate versions, I believe you can choose it when uploading?

**Comment by db0** [comment]
Huh interesting. I'll check

**Comment by otDan** [comment]
did you have time to check it out? if it doesn't work I can probably just ask in the godot discord

**Comment by db0** [comment]
No sorry, I've been very busy. I'll look into it as soon as I can

**Comment by db0** [comment]
Looks like there's a bug

image

Also I've done some more changed on the main branch you need to onboard. It's going to be a bit of a PITA to keep this synced with 3.x features.

**Comment by otDan** [comment]
I don't have that issue, are you using the latest godot 4 version? 
image

**Comment by db0** [comment]
Yes, just downloaded it. I'll try again in case it was a fluke

**Comment by otDan** [comment]
it wasn't a fluke, for some reason I wasn't getting that problem till I pulled it again, I will update it in the next days including the changes you made

**Pull request merged**
